# Generated by Django 3.1.3 on 2021-01-07 05:44

from django.db import migrations, models
import publications.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal_abbreviation',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='publication',
            name='location',
            field=models.CharField(blank=True, help_text='The location where this work was published.', max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='book_title',
            field=models.CharField(blank=True, help_text='If this work is book section, the title of the larger work.', max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='institution',
            field=models.CharField(blank=True, help_text='If this work is a thesis, the institution where it was completed.', max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=publications.fields.PagesField(blank=True, help_text='The full range of pages of this work if it is not a complete book.', max_length=32),
        ),
    ]
