# Generated by Django 3.1.3 on 2021-04-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20210107_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='media_public',
            field=models.BooleanField(default=False, help_text='Whether or not any media files for this publication should be accessible publicly.'),
        ),
    ]
