# Generated by Django 3.1.3 on 2021-05-03 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_publication_media_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator(code='invalid_doi', message='Invalid DOI.', regex='^10.\\d{4,9}\\/[\\-._;()\\/:A-Z0-9a-z]+$')], verbose_name='DOI'),
        ),
    ]
