# Generated by Django 3.1.3 on 2021-07-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='locator',
            field=models.CharField(default='', help_text='The location in the publication for this reference (i.e. the page number).', max_length=255),
        ),
    ]
