# Generated by Django 3.1.3 on 2021-08-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20210719_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='locator',
            field=models.CharField(blank=True, default='', help_text='The location in the publication for this reference (i.e. the page number).', max_length=255),
        ),
    ]
