# Generated by Django 3.1.3 on 2021-08-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_auto_20210801_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['publication__year', 'publication__authors', 'locator']},
        ),
    ]
